# GitLab CI Pipeline Configuration
stages:
  - test

rust-tests:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  stage: test
  image:
    name: registry.gitlab.rylanswebsite.com/rylan-meilutis/rust-docker-builder:x86
  script:
    - chmod +x build.sh && ./build.sh test

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

