# GitLab CI Pipeline Configuration
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

stages:
  - test

rust-tests:
  stage: test
  image:
    name: registry.gitlab.rylanswebsite.com/rylan-meilutis/rust-docker-builder:x86
  script:
    - chmod +x build.py && ./build.py test

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

